#! /bin/zsh
#lsdl

# mode check
if [ "$1" = "-m" ];then
    if [ -p /dev/stdin ];then
        file=$(cat -)
    else
        echo "Dump your urls and press esc:"
        read -d $'\e' file
    fi
    [ "$file" = "" ] && exit
    filename=$2
    [ "$2" = "" ] && printf "\rFilename:" && read filename < /dev/tty
    echo $file > $filename.dls && echo "$filename.dls($(echo $file | grep -c '') lines) successfully created." >&2
    exit
fi

# Change the iterator
IFS_BAK=$IFS
IFS=$'\n'

# Get .dls files
dlss=($(ls -1|grep -e ".dls$"))

for dls in $dlss;do
# Get url list
urls=($(cat $dls|grep "^\(http\|https\)://"))
[ $#urls[@] -eq 0 ] && echo "$dls:no urls" 
# Take .dls and make directory
dlsfolder=$(echo $dls| sed "s/\.dls//" )
mkdir $dlsfolder
# cd to the folder
cd $dlsfolder
# loop the list and download every url
for url in $urls;do
wget -nv $url >&2
done
# cd to one above
cd ../
# mv the urllist to the directory and rename it
mv $dls $dlsfolder/receipt
done

IFS=$IFS_BAK
